language: node_js
node_js:
  - 14
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
scripts:
  - yarn install
  - yarn lint
  - yarn run test:coveralls
